export const PROJECTS = [
    { src: './assets/images/projects images/22.png', link: 'https://www.alfa-sa.co/home', address: "alfa care", project: "alfa care app provides you with a variety of home health medical services provided by the best healthcare centers." },
    { src: './assets/images/projects images/12.png', link: 'https://uat-app.alfa-sa.co/login', address: "alfa care dashboard", project: 'A dashboard for hospitals and clinics to add booking appointments and available services' },
    { src: './assets/images/projects images/17.png', link: 'https://uat-admin.alfa-sa.co/login', address: "alfa care", project: 'alfa care dashboard' },
    { src: './assets/images/projects images/11.png', link: '', address: "morona tec", project: 'morona tec dashboard' },
    { src: './assets/images/projects images/3.png', link: 'https://weather-76d954.netlify.app/', address: "weather App", project: 'Weather app to clarify the weather for three days' },
    { src: './assets/images/projects images/8.png', link: 'https://emanmagdy294.github.io/interview-questions/', address: "Interview Question", project: 'Interview Question provided to front-end developers such as html,css,js....' },
    { src: './assets/images/projects images/1.png', link: 'https://hello-985f87.netlify.app', address: "Template UI", project: 'Party hello world' },
    { src: './assets/images/projects images/2.png', link: 'https://restaurant-website-77592d.netlify.app', address: "Template UI", project: 'Template restaurants' },
    { src: './assets/images/projects images/4.png', link: 'https://beauty-salon-4bf7c0.netlify.app', address: "Template UI", project: 'Beauty Salon' },
    { src: './assets/images/projects images/5.png', link: "https://cook-books-e1bc3e.netlify.app", address: "Cookbooks", project: 'Cookbooks to teach women how to cook' },
    { src: './assets/images/projects images/6.png', link: 'https://tender-feynman-18ecca.netlify.app', address: "Techunique Company", project: 'Techunique Website' },
    { src: './assets/images/projects images/7.png', link: '', address: "Soumtech", project: 'Soumtech website' },
    { src: './assets/images/projects images/14.png', link: 'https://mystifying-lamarr-e93487.netlify.app', address: "Khaled Saad Optics", project: 'Website to buy glasses' },
    { src: './assets/images/projects images/23.png', link: "ttps://651e71297f12685d79ab33e6--genuine-chimera-84d408.netlify.app/#/home", address: "Template by react", project: 'A site for viewing movies and series' },
    { src: './assets/images/projects images/9.png', link: 'https://heuristic-fermi-1fb0bc.netlify.app', address: 'UDG Website', project: "UDG Website" },
    { src: './assets/images/projects images/10.png', link: 'https://vibrant-mccarthy-fb3097.netlify.app', address: 'UG Pharma', project: 'UG Pharma Website' },
    { src: './assets/images/projects images/13.png', link: '', address: "Zawil", project: 'Zawil Website' },
    { src: './assets/images/projects images/15.png', link: 'https://quirky-sammet-541fd3.netlify.app', address: "Bussma Realestate Development", project: 'Bussma Realestate Development Website' },
    { src: './assets/images/projects images/18.png', link: 'https://xenodochial-carson-134115.netlify.app', address: "Template UI", project: "Template UI" },
    { src: './assets/images/projects images/19.png', link: 'https://serene-raman-88c1ba.netlify.app/', address: "Template UI", project: "Template UI" },
    { src: './assets/images/projects images/20.png', link: 'https://emanmagdy294.github.io/skinPlans/', address: "Skin Plans", project: 'Skin Plans Website' },
    { src: './assets/images/projects images/21.png', link: "https://emanmagdy294.github.io/covid19/", address: "Template UI", project: 'Covid19' }
]